name: CellProfiler CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-cellprofiler:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------------------------------
      # 1. Checkout repo
      # -------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------------------------------
      # 2. Build Docker image
      # -------------------------------------------------------
      - name: Build CellProfiler image
        run: |
          docker build -t cellprofiler-headless .

      # -------------------------------------------------------
      # 3. Create test folders
      # -------------------------------------------------------
      - name: Prepare test directories
        run: |
          mkdir -p input_images
          mkdir -p output_results

      - name: Add sample pipeline
        run: |
            mkdir -p pipelines
            echo "dummy" > pipelines/my_pipeline.cppipe
      
      - name: Verify pipeline exists
        run: |
            test -f pipelines/my_pipeline.cppipe

      - name: Verify images
        run: |
            find input_images -type f

      - name: Run CellProfiler
        run: |
            docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            cellprofiler-headless \
            cellprofiler \
                -c \
                -r \
                -p /workspace/pipelines/my_pipeline.cppipe \
                -i /workspace/input_images \
                -o /workspace/output_results
      
      # -------------------------------------------------------
      # 5. Run CellProfiler headless
      # -------------------------------------------------------
      - name: Run CellProfiler pipeline
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            cellprofiler-headless \
            cellprofiler \
              -c \
              -r \
              -p /workspace/pipeline.cppipe \
              -i /workspace/input_images \
              -o /workspace/output_results

      # -------------------------------------------------------
      # 6. Upload outputs
      # -------------------------------------------------------
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: cellprofiler-output
          path: output_results